### ISSUE TITLE
Importing projects with non-default domain requires parent project

### ISSUE THREAD

**Issue by tatsuyaamemiya** [os-migrate/os-migrate#403]
I tested importing and exporting the project with non-default domain with the latest commit 
https://github.com/os-migrate/os-migrate/commit/6aa3ca69b0bee1dfb9f035477ea8881bc95573ac in my internal environment, it requires the parent project while importing regardless the source cloud did not have the one. Importing the project failed. After creating the parent project as well as the domain in the destination cloud, import of the project finished successfully.

Source cloud has the following domains and projects. Project "Kanagawa" was created by `openstack create project --domain JPN Kanagawa`.
```
(overcloud) [stack@sep-u ~]$ openstack domain list
+----------------------------------+------------+---------+--------------------+
| ID                               | Name       | Enabled | Description        |
+----------------------------------+------------+---------+--------------------+
| 706f7fd9fa2942be984bb2a6e0bb75a8 | JPN        | True    |                    |
| 80842325226840bcbddacaae6c54d442 | heat_stack | True    |                    |
| default                          | Default    | True    | The default domain |
+----------------------------------+------------+---------+--------------------+
(overcloud) [stack@sep-u ~]$ openstack project list --long
+----------------------------------+----------+----------------------------------+-----------------------------------+---------+
| ID                               | Name     | Domain ID                        | Description                       | Enabled |
+----------------------------------+----------+----------------------------------+-----------------------------------+---------+
| 36f6ed1deefd4f9d89197fed7484c79c | admin    | default                          | admin tenant                      | True    |
| 6192fb2f7d0c4c0095780975c2ab3aee | service  | default                          | Tenant for the openstack services | True    |
| c9f4abb71b434d76a92236df68a0c625 | Kanagawa | 706f7fd9fa2942be984bb2a6e0bb75a8 |                                   | True    |
+----------------------------------+----------+----------------------------------+-----------------------------------+---------+
(overcloud) [stack@sep-u ~]$ openstack project show Kanagawa
+-------------+----------------------------------+
| Field       | Value                            |
+-------------+----------------------------------+
| description |                                  |
| domain_id   | 706f7fd9fa2942be984bb2a6e0bb75a8 |
| enabled     | True                             |
| id          | c9f4abb71b434d76a92236df68a0c625 |
| is_domain   | False                            |
| name        | Kanagawa                         |
| parent_id   | 706f7fd9fa2942be984bb2a6e0bb75a8 |
| tags        | []                               |
+-------------+----------------------------------+
```

The exported project "Kanagawa" is as follows.
```
[root@migrator ~]# cat os-migrate-data/projects.yml
os_migrate_version: 0.8.0
resources:
- _info: {domain_id: 706f7fd9fa2942be984bb2a6e0bb75a8, id: c9f4abb71b434d76a92236df68a0c625,
    parent_id: 706f7fd9fa2942be984bb2a6e0bb75a8}
  _migration_params: {}
  params:
    description: ''
    domain_ref: {domain_name: null, name: JPN, project_name: null}
    is_domain: false
    is_enabled: true
    name: Kanagawa
    parent_ref: {domain_name: null, name: JPN, project_name: null}
  type: openstack.identity.Project
```

This requires the parent project "JPN" in the destination cloud while it does not exit in the source cloud. I created the domain "JPN" only before importing, as the same state as the source cloud. I am not sure if keystone itself works as designed because it set parent_id as well while "openstack create project --domain" command, but is there any place to improve the behavior in os-migrate side?
