### ISSUE TITLE
Remove Devstack hack for Fedora 29

### ISSUE THREAD

**Issue by jistr** [os-migrate/os-migrate#65]
Being added in pull request #64 into `toolbox/vagrant/ansible/roles/devstack/tasks/config.yml`:

```yaml
- name: hack devstack until we switch to Fedora 30 or CentOS 8
  lineinfile:
    path: /home/stack/devstack/lib/nova
    regexp: sudo dnf copr enable -y iwienand/iscsi-initiator-utils
    state: absent
```
