### ISSUE TITLE
'cloud_vars_src' is undefined during import_workload

### ISSUE THREAD

**Issue by TatusGepetto** [os-migrate/os-migrate#712]
I can easily export/import all data (networks/subnets/security groups etc) between both clouds, but when I'm trying to import my VM I hit a below issue:

```
TASK [os_migrate.os_migrate.import_workloads : Set block_storage_api_version for source cloud is defined] *************************************************************************************************************************************************************************
task path: /home/kollaprov/.ansible/collections/ansible_collections/os_migrate/os_migrate/roles/import_workloads/tasks/workload.yml:75
skipping: [localhost] => {"changed": false, "false_condition": "os_migrate_src_block_storage_api_version is defined", "skip_reason": "Conditional result was False"}

TASK [os_migrate.os_migrate.import_workloads : expose source volumes] *************************************************************************************************************************************************************************************************************
task path: /home/kollaprov/.ansible/collections/ansible_collections/os_migrate/os_migrate/roles/import_workloads/tasks/workload.yml:83
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'cloud_vars_src' is undefined\n\nThe error appears to be in '/home/kollaprov/.ansible/collections/ansible_collections/os_migrate/os_migrate/roles/import_workloads/tasks/workload.yml': line 83, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: expose source volumes\n      ^ here\n"}

TASK [os_migrate.os_migrate.import_workloads : clean up in the source cloud after migration failure] ******************************************************************************************************************************************************************************
task path: /home/kollaprov/.ansible/collections/ansible_collections/os_migrate/os_migrate/roles/import_workloads/tasks/workload.yml:158
skipping: [localhost] => {"changed": false, "false_condition": "exports is defined and 'volume_map' in exports", "skip_reason": "Conditional result was False"}

TASK [os_migrate.os_migrate.import_workloads : clean up in the destination cloud after migration failure] *************************************************************************************************************************************************************************
task path: /home/kollaprov/.ansible/collections/ansible_collections/os_migrate/os_migrate/roles/import_workloads/tasks/workload.yml:180
skipping: [localhost] => {"changed": false, "false_condition": "exports is defined and 'volume_map' in exports", "skip_reason": "Conditional result was False"}

TASK [os_migrate.os_migrate.import_workloads : fail if there was a problem in the migration] **************************************************************************************************************************************************************************************
task path: /home/kollaprov/.ansible/collections/ansible_collections/os_migrate/os_migrate/roles/import_workloads/tasks/workload.yml:203
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import local-disk-instance."}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=43   changed=3    unreachable=0    failed=1    skipped=11   rescued=1    ignored=0   

```

Is there a way how to skip it? 
My vars file looks as below:

```
os_migrate_src_auth:
  auth_url: https://kolla.my.cloud.pl:5000/v3
  password: 123
  project_domain_name: Default
  project_name: myTestUser1
  user_domain_name: Default
  username: myTestUser
os_migrate_src_region_name: KOLLA_DEVEL
os_migrate_dst_auth:
  auth_url: http://kolla.test.my.cloud.pl:5000/v3
  password: 3456
  project_domain_name: Default
  project_name: project-myTestUser
  user_domain_name: Default
  username: myTestUser
os_migrate_dst_region_name: KOLLA_TC

os_migrate_data_dir: /home/kollaprov/os-migrate-data
os_migrate_conversion_flavor_name: m6.c2
os_migrate_src_conversion_external_network_name: EXTERNAL-NEW
os_migrate_dst_conversion_external_network_name: EXTERNAL-PUB

os_migrate_src_conversion_host_boot_from_volume: true
os_migrate_dst_conversion_host_boot_from_volume: true
os_migrate_src_conversion_host_volume_size: 50
os_migrate_dst_conversion_host_volume_size: 50
```

I was able to deploy a conversion host. Thanks in advance for help
